### ISSUE TITLE
[Bug]: No option to disable dimensional warp message

### ISSUE THREAD

**Issue by Rad233** [someaddons/FallingThroughMod#11]
### Describe the bug you're experiencing

There's neither an option to disable the message when you are close to the bedrock layer, nor a translation key. 

### Reproducability

Install the mod. 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Fabric

### Logs

https://gist.github.com/Rad233/e2dba929477f674506d6817a5bd38174

**Comment by someaddons** [comment]
old fabric versions are no longer updated

**Comment by Rad233** [comment]
> old fabric versions are no longer updated

Can I release a fork, or create a fabric 1.18.2 pull request here?
