### ISSUE TITLE
1.20.1 The mod kind of works whenever it wants to

### ISSUE THREAD

**Issue by Aabaddon** [someaddons/FallingThroughMod#12]
### Describe the bug you're experiencing

i tested a milion times trying to make this mod work with amplified nether, when it finally started teleporting me where it had to i made a server to play with friends, then when the time to get to the nether finally came we made a hole in the bedrock and jumped straight in because the mod was "working", sadly everyone just died and lost absolutelly everything

### Reproducability

-install the mod with amplified nether

-change the height where the nether teleports you back to 230 (and the height you teleport inside 220) without touching the -60 from the overworld

-jump to the void

-lose your progress.

the "minecraft version" option wont let me select 1.20.1 but that is the version

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

no log

**Comment by someaddons** [comment]
cannot reproduce it, please attach the config and the latest.log during the issue. My guess is its a mod conflict
