### ISSUE TITLE
[Bug]: 1.19 bug dim stacking will not work

### ISSUE THREAD

**Issue by Joshernoob** [someaddons/FallingThroughMod#14]
### Describe the bug you're experiencing

have a very basic pack set up I'm making, added this to make the overworld go into the deeper darks otherside, first i tested it with the base configs and nothing

when you hit were your meant to telaport you instead take normal damage even creative damage you take

From Testing with the mod in a blank game with no other mods 

forgivingworld-1.19.2-4.2: This will do nothing on falling into the void

forgivingworld-1.19.2-4.1 and forgivingworld-1.19.2-4.0: they both will show chat messages but won't telaport you and after first time just stops working all together

the others don't work at all

Logs are for the latest version of the mod with the latest core.

### Reproducability

Back install of modded 1.91.2 with 
Forge 43.3.5 
Any Cubbord version (I used latest)
Any Version of this mod (I went threw them All)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/Joshernoob/dfcc49d800d9736ba68c80ba92fbaa66

**Comment by someaddons** [comment]
Did you test in survival mode? creative mode players are unaffected
