### ISSUE TITLE
[Bug]: Incompatible with Incendium/Amplified Nether in 1.18.2 Forge 

### ISSUE THREAD

**Issue by Mystifyed** [someaddons/FallingThroughMod#15]
### Describe the bug you're experiencing

I am trying to set Dimension Border TP Distance to -60, since the Incendium Nether Border is 64 blocks higher. However, the game seems to ignore this and the teleport never triggers at all, and no chat messages appear. I've tested in Survival and the same thing happens.

### Reproducability

N/A

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

N/A

**Comment by someaddons** [comment]
ye the mod uses the world height, and incendium datapack/mod does not properly set that one
