### ISSUE TITLE
[Bug]:  1.20.1 Game crash (and world becomes unrecoverable) when attempting to teleport player

### ISSUE THREAD

**Issue by Orinai** [someaddons/FallingThroughMod#17]
### Describe the bug you're experiencing

**1.20.1**

Trying to sort out if this is an issue with a mod incompatibility, my config file, or the mod itself. As soon as teleport would be triggered, the game locks up, crashes, and then anytime I try to load the same world, it crashes again. Attaching My config file, as well as the crash report.

There are a lot of mods, but because of interdependencies it's hard for me to disable them for testing. Just trying to narrow down if it seems like a compatibility issue, something with my config settings, or the mod itself.

[forgivingworld.json](https://github.com/someaddons/FallingThroughMod/files/14534583/forgivingworld.json)

[crash-2024-03-08_01.17.29-server.txt](https://github.com/someaddons/FallingThroughMod/files/14534614/crash-2024-03-08_01.17.29-server.txt)

[latest.log](https://github.com/someaddons/FallingThroughMod/files/14534616/latest.log)

### Reproducability

- Run game with attatched config and modlist
- dig down to initiate teleportation
- crash

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

java.lang.NoSuchMethodError: 'net.minecraft.core.BlockPos com.cupboard.util.BlockSearch.findAround(net.minecraft.server.level.ServerLevel, net.minecraft.core.BlockPos, int, int, int, java.util.function.BiPredicate)'

**Comment by Sacri-Pan** [comment]
I had the same issues, I tried to run several tries on a testing instances.

Try to downgrade to 4.2, it worked for me!

**Comment by Orinai** [comment]
> I had the same issues, I tried to run several tries on a testing instances.
> 
> Try to downgrade to 4.2, it worked for me!

Ok, that did indeed work. seems like something in 4.3 breaks everything

**Comment by someaddons** [comment]
fixed in 4.4
