### ISSUE TITLE
[1.20.1 - Mod version: 4.2 - Bug/Suggestion]: Ability to enter void/island dims

### ISSUE THREAD

**Issue by Crankonator** [someaddons/FallingThroughMod#18]
Right now it seems there isnt a proper way of entering void/island dimensions from the bottom up.
Using aether/the end as an example, I build up to the set ylevel required to enter aether from the overworld, meaning i should enter at the bottom of aether... i wait for the teleport... I spawn in the void and die...

It would be nice if it either had an option to spawn a block under you as you enter the dimension, or had the option to spawn you at the nearest solid block upon entering

**Comment by someaddons** [comment]
```
    {
      "from": "minecraft:overworld",
      "to": "minecraft:the_end",
      "teleporttype": {
        "teleporttype": "GROUND",
        "teleport_to_y": 120
      },
      "abovey": 100
    }
    
   Allows you to teleport bottom up, GROUND/CAVE types search for a block to stand upon
