### ISSUE TITLE
[Bug]: When falling through to world blender dimension i'm dying from fall damage most of the time

### ISSUE THREAD

**Issue by JetpackRescue** [someaddons/FallingThroughMod#2]
### Describe the bug you're experiencing

When using the mod World Blender which adds a dimension that combines everything from every dimension, i'm dying from fall damage most of the time when falling through to that dimension. The drop from the top of the world is typically pretty far, so you're falling for quite a distance sometimes, not sure if that has anything to do with it?

https://www.curseforge.com/minecraft/mc-mods/worldblender

### Reproducability

install world blender, fall through to that dimension, die.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

None

**Comment by someaddons** [comment]
the slowfall is limited intentionally, it is only lasting so that you normally do not die but still take a bit of falldamage in the overworld.  But worldblender is not really a dimension of "normal " so I wouldnt say thats a bug^^
