### ISSUE TITLE
[Bug]: Adding dimensions above overworld seems not to work

### ISSUE THREAD

**Issue by ThePiekar** [someaddons/FallingThroughMod#22]
### Describe the bug you're experiencing

I tried to make going above a certain height in overworld teleport the player to the end, it doesn't work.

### Reproducability

Simply replace the "to" dimension to "minecraft:the_end" in the entry that usually teleports the player back down when exceeding y level 364, the rule stops working.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1 

### Modloader version

Forge

### Logs

N.A.

**Comment by someaddons** [comment]
Works just fine for me
```
    {
      "from": "minecraft:overworld",
      "to": "minecraft:the_end",
      "teleporttype": {
        "teleporttype": "GROUND",
        "teleport_to_y": 70
      },
      "abovey": 264,
      "slowfallticks": 400
    },
