### ISSUE TITLE
[Bug]: Configuration Refreshing to Default.

### ISSUE THREAD

**Issue by Restoredbug808** [someaddons/FallingThroughMod#24]
### Describe the bug you're experiencing

I added 14 connections of dimensions in the configuration only for it to refresh back to the default when loading up the game. It works just fine with 6 dimensions added.

### Reproducability

Just add 7 dimensions or above and it'll refresh. The dimensions that is used are from the mods called "aether:the_aether" and "oreportal_forge:[anyorerelated]dimension"

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/Restoredbug808/15b73b84a21a7b6d79b963e3615c0d4c

**Comment by someaddons** [comment]
you're missing commata behind all the
"abovey": 175" 
where there is a second entry below like  "slowfallticks": 800


Its probably always a good idea to use sth like https://jsonlint.com/ to validate the json file
