### ISSUE TITLE
[Bug]: Teleporting not working correctly

### ISSUE THREAD

**Issue by Karma-Fox** [someaddons/FallingThroughMod#3]
### Describe the bug you're experiencing

Using the Direwolf20 1.18.2 mod pack. Nether ceiling seems to be MUCH higher then 127 in this pack but mod still forces a teleport at 127. On top of that, when being teleported from the nether to the overworld, it spawns you at Y30 instead of -64.

### Reproducability

Install this with the Direwolf20 1.18.2 mod pack, use this setting
`aboveDimension = ["minecraft:the_nether;minecraft:overworld;0.125;0.125;CAVE;4", "minecraft:overworld;minecraft:overworld;0.8;0.8;AIR;0"]`
and try to reach the ceiling of the nether.

Using fallingthrough-1.18.2-2.4.jar

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

n/a

**Comment by someaddons** [comment]
Tested it, the amplified nether mod doesnt up the dimension height as intended and thus the mod thinks its not as high

**Comment by Karma-Fox** [comment]
The pack I am using doesn't have the amplified nether mod in it.

![image](https://user-images.githubusercontent.com/75238752/174822376-f8cf957e-de01-4107-98e7-e554a9c6a673.png)


As you can see from the image, I am standing at 124 and there is still a lot more before hitting the ceiling.

**Comment by Karma-Fox** [comment]
Figured out what changes the nether height, it would be Incendium, a datapack, https://www.curseforge.com/minecraft/mc-mods/incendium

**Comment by someaddons** [comment]
ye that datapack has the same issue
