### ISSUE TITLE
[Bug]: When playing with other people, you'll get teleported based off host dimension, not your own.

### ISSUE THREAD

**Issue by Jetpack-Cat** [someaddons/FallingThroughMod#4]
### Describe the bug you're experiencing

Pretty critical bug, as I just released a modpack where dimensional fall through is essential to traveling between dimensions(7 dimensions in total). When playing with a friend, if you have multiple fall through dimensions, the dimension you teleport to will be based off the hosts dimension.

For example: This is how my dimensions are set up:

Overworld
Nether
World_blender

If the host is in the overworld and another player falls through from the overworld, they'll teleport to the nether.
BUT, if the host is in the nether and you're in the overworld, you'll fall through to the world_blender dimension. So you'll never fall through to the same dimension unless the non-host players all fall through to the nether first, since it's based off the hosts dimension.

### Reproducability

Have the host be in a different dimension from other players. Then have other player fall through dimension. The non-host players fall through dimensional teleport will be based off the host players dimension, not their own.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/Jetpack-Cat/cd7831009e6cf042b030559ee7825545

**Comment by NickChamberlin** [comment]
I'm also having this issue do you plan on fixing it

**Comment by someaddons** [comment]
The teleportation is based on the falling player, other players have nothing to do with that. Also what is a "host" dimension? are we talking of open to lan here? if so thats generally not supported anyways

**Comment by Jetpack-Cat** [comment]
The host dimension when playing on LAN is the dimension the host player is currently in. The only dimension stacking mod that has this issue is this mod. The dimensional teleport in this mod is determined off the host players dimension. If the host is in the overworld, other players who fall through from any dimension will always end up in the nether, because it's determined by what dimension the host player is in.

I ended up having to switch to a different mod, as dimension stacking is the only way to travel to different dimensions in my modpack, so it working correctly is critical.

**Comment by someaddons** [comment]
Works fine for me using a proper server, and since its lan mode which I don't actively support I'll just close this
