### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Tellik** [someaddons/FallingThroughMod#5]
### Describe the bug you're experiencing

Went to Y -63.

Chat messages of: "Dimensional forces are starting to affect you, pulling you down, take care!" and "Dimensional forces are getting stronger..."

Then nothing happens.

### Reproducability

Attempt to use the mod.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

https://gist.github.com/Tellik/d90354dfb7d5740127455338a7db978e

**Comment by marewey** [comment]
Having same issue in 1.19.2 version

**Comment by marewey** [comment]
Seems to be only in creative this happens. I too was confused.

**Comment by someaddons** [comment]
ye creative players are intentionally excluded
