### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kezmodius** [someaddons/FallingThroughMod#6]
### Describe the bug you're experiencing

Two players today on the Minecolonies - Cities Skylands Patreon server were teleported from the Nether into the Overworld past the world border and died.

(Copypasted from Discord in case you want to check the server log)
Mc2Disc BOT  — Today at 15:19
Ewout_ suffocated in a wall

Mc2Disc BOT — Today at 15:11
TheEnderBot suffocated in a wall

### Reproducability

It happened twice within 8 minutes. 
It didn't happen to me, I was only a virtual witness, so I do not have all the information.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

Please check the server logs

**Comment by someaddons** [comment]
fixed
