### ISSUE TITLE
[help wanted]: Teleporting to a different dimension causes you to go under bedrock even if belowY is defined.

### ISSUE THREAD

**Issue by TechSupportRed** [someaddons/FallingThroughMod#9]
### Describe the bug you're experiencing

Hi, I noticed that the belowY cord requires you to be under the bedrock for you to teleport, and you have to fall a far distance before being teleported to the other dimension, is there anyway around this or able to replace the bedrock with obsidian or something. As I am making a modpack that has multiple layers of caves. I've tried setting the belowY to above bedrock but it just doesn't teleport me unless I go through the bedrock which is not what I am aiming for

### Reproducability

Here is what I have put in the json file for now.
```
  },
  "dimensionconnections": [
    {
      "from": "minecraft:overworld",
      "to": "infinite_abyss:first_layer",
      "xcoordmultiplier": 1,
      "zcoordmultiplier": 1,
      "teleporttype": {
        "teleporttype": "AIR",
        "teleport_to_y": 120
      },
      "belowy": -48,
      "slowfallticks": 400
    },
```

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/TechSupportRed/0d7f5c2f628385263c5c2ee5015998c3

**Comment by someaddons** [comment]
it teleports on void damage, or after a while of being below the given Y level. It does however not teleport creative mode players, I guess you tested only in creative?^^
